name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - fastparquet=2022.11.0
  - jupyterlab=3.0.12
  - ipywidgets
  - pip:
      - wandb==0.12.18
      - pandas-profiling