name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.0.1
  - hydra-core=1.0.6
  - matplotlib=3.2.2
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3
  - ipython
  - notebook
  - jupyterlab
  - cookiecutter
  - pip:
      - wandb==0.12.18
