name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - mlflow=2.0.1
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.10
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib=3.3.4
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - plotly=4.4.1
  - pillow=8.1.2
  - scipy=1.6.1
  - pytest=6.2.2
  - fastparquet=2022.11.0
  - git=2.30.2
  - pip=20.3.3
  - protobuf=3.20.1
  - seaborn
  - pip:
      - wandb==0.12.18
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
      - omegaconf==2.0.6
      - hydra-joblib-launcher==1.1.2
      - pandas-profiling
