name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - mlflow=2.0.1
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - plotly=4.4.1
  - pillow=8.1.2
  - hydra-core=1.0.6
  - protobuf=3.20.1
  - pip:
      - wandb==0.12.18
      - omegaconf==2.0.6
      - hydra-joblib-launcher==1.1.2
